# Social keys
SOCIAL_AUTH_TWITTER_KEY = 'SuYEIzRC8ib3DHRQuiK9u8gYf'
SOCIAL_AUTH_TWITTER_SECRET = 'EPO2cRMesQj7Ab2PGLCmvlM5hN5i5TDXR4eFZZLDql4tPZVDRV'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'